### ISSUE TITLE
Задание для 1 уровня

### ISSUE THREAD

**Issue by Tako-San** [Tako-San/OpenCL#1]
Задача: отсортировать входную последовательность на видеокарте,
используя bitonic sort
***Входные данные***: число элементов N, далее N несортированных элементов
***Выходные данные***: сортированная последовательность

Формальное описание алгоритма:

* Bitonic split: для каждого 𝑖 от 0 до 𝑁/2 − 1 сравним его с 𝑖 + 𝑁/2 и если он
больше, обменяем их местами
* В итоге получится последовательность, каждая половина которой bitonic и
правая строго больше левой
* Bitonic merge: проведём bitonic splits до уровня двух элементов, после чего
последовательность отсортирована
* Осталось понять как привести некую последовательность к bitonic shape
* Понятно, что любые два элемента уже bitonic shape. Что дальше?
* Итак, если мы отсортировали подпоследовательности из двух элементов,
делая левую возрастающей а правую убывающей, мы получили две
последовательности из четырёх элементов

**Comment by derzhavin3016** [comment]
[Битонная сортировка](https://ru.m.wikipedia.org/wiki/Битонная_сортировка)

**Comment by Tako-San** [comment]
* [OpenCL specification](https://www.khronos.org/registry/OpenCL/specs/opencl-1.2.pdf)
* [Matthew Scarpino OpenCL in action](http://analog.nik.uni-obuda.hu/ParhuzamosProgramozasuHardver/02_GPGPU-Irodalom/03_CUDA-Irodalom_LovasIstvan/OpenCl/Books/%5BMatthew_Scarpino%5D_OpenCL_in_Action_How_to_Accele(Bookos.org).pdf)

**Comment by derzhavin3016** [comment]
[OpenCL c++ wrapper](https://www.khronos.org/registry/OpenCL/specs/opencl-cplusplus-1.2.pdf)

**Comment by uslsteen** [comment]
[Установка OpenCL wrapper](https://medium.com/@georgimweb/how-to-install-opencl-linux-intel-bcbfc2821274)

**Comment by Tako-San** [comment]
[Методичка](https://cims.nyu.edu/~schlacht/OpenCLModel.pdf)

**Comment by uslsteen** [comment]
[книга по OpenCL](http://asu-cs.donntu.org/sites/default/files/images/doc/opencl.programming.guide.pdf)

**Comment by derzhavin3016** [comment]
[OpenCL API](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/pdf/OpenCL_API.pdf)

**Comment by uslsteen** [comment]
[For undestanding OpenCL terms](https://downloads.ti.com/mctools/esd/docs/opencl/execution/kernels-workgroups-workitems.html)

**Comment by uslsteen** [comment]
[Book with used algorithm, page 262](http://3.droppdf.com/files/aGywp/opencl-programming-by-example.pdf)
